DROP DATABASE IF EXISTS ALARMSYS;

CREATE DATABASE ALARMSYS;

CREATE USER 'alarmsys'@'localhost' IDENTIFIED BY 'abc@123.';
GRANT INSERT, SELECT ON ALARMSYS.* TO 'alarmsys'@'localhost';

USE ALARMSYS;

CREATE TABLE DETECCAO
(
	DETE_ID_DETECCAO INT AUTO_INCREMENT,
	DETE_VL_DISTANCIA INT NOT NULL,
	DETE_DT_DETECCAO DATETIME NOT NULL,
	PRIMARY KEY (DETE_ID_DETECCAO)
);