DROP DATABASE IF EXISTS ALARMSYS;
DROP USER IF EXISTS 'monitor'@'localhost';

CREATE DATABASE ALARMSYS;
CREATE USER 'monitor'@'localhost' IDENTIFIED BY 'ifes2018';
GRANT INSERT, SELECT ON ALARMSYS.* TO 'monitor'@'localhost'; 

USE ALARMSYS;

CREATE TABLE DETECCAO
(
	DETE_ID_DETECCAO 		INT NOT NULL AUTO_INCREMENT,
	DETE_VL_DISTANCIA_MEDIA 	DECIMAL(5, 2) NOT NULL,
	DETE_DT_DETECCAO 		DATETIME NOT NULL,
	PRIMARY KEY (DETE_ID_DETECCAO)
);

CREATE TABLE TOKEN
(
	TOKE_ID_TOKEN			VARCHAR(152)	NOT NULL,
	TOKE_DT_CADASTRO		DATETIME 	NOT NULL,
	PRIMARY KEY (TOKE_ID_TOKEN)
);
